### ISSUE TITLE
Bkg plots from filtered (clean) events/gti files

### ISSUE THREAD

**Issue by sguillot** [paulray/NICERsoft#33]
I think it could also be useful to plot the BKG plots once all the filtering has been performed. This would be a useful diagnostic of what could still cause count rates variations.

But this means giving the housekeeping files as well as the clean event file...I haven't really figure out how to do this.  Any suggestions?

**Comment by paulray** [comment]
Probably we just need to create a filtered .mkf file in the _pipe directory based on the final GTI (maybe with `fltime`), then use that to make the plots.

I've also been meaning to update the code to make the bkg plots from the mkf file entirely, instead of computing from the events, since all those new columns have been added. That should speed up psrpipe a lot.
